import Head from 'next/head'
import Home from '@/pages/home';

export default function Index() {
  return (
    <>
      <Head>
        <title>PC Launcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/13722976.jpeg" />
      </Head>
      <Home />
    </>
  )
};
